Repository hmcts/ccd-definition-store-api, pull requests merged in 2018-10, with the labels that each got.

#170 [PREVIEW] RDM-2918: Database table definition for "definition_designer" table
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-2918.xml
Labels: checkpoint

#177 [PREVIEW] RDM-3132: Instantiate Azure Storage components conditionally
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/AzureStorageConfiguration.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/service/AzureBlobStorageClient.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/service/FileStorageService.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/ImportController.java
Labels: checkpoint

#107 RDM-114 Case Link
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-114.xml
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
Labels: checkpoint

#174 RDM-2917 DB cleanup scripts
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/AzureStorageConfiguration.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/service/AzureBlobStorageClient.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/ImportController.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/RestResponseEntityExceptionHandler.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/DateTimeStringGenerator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/service/AzureBlobStorageClientTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/service/FileStorageServiceTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/ImportControllerTest.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-2917-cleanup.xml
Labels: enhancement

#186 RDM-3144 CCD displays 3 events all called ‘Apply for a divorce’ when logged in with solicitor account
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/BaseTest.java
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/excel/SpreadSheetImportTest.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationErrorMessageCreator.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityACLValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityCrudValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityInvalidCrudValidationError.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityACLValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityCrudValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityACLValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityCrudValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityInvalidCrudValidationError.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/state/StateEntityACLValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/state/StateEntityCrudValidatorImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/UserRoleServiceImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/metadata/MetadataFieldServiceImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityCrudValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityACLValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityCrudValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityInvalidCrudValidationErrorTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityInvalidUserRoleValidationErrorTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityStateValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/complexfield/ComplexFieldEntityShowConditionValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityCrudValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/state/StateEntityCrudValidatorImplTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseEventParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseFieldParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseStateParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseTypeParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/CaseTypeParser.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreatorTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseEventParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseFieldParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseStateParserTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeLiteACLEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeLiteEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventLiteACLEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventLiteEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/StateEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/StateLiteEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseEventLite.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseStateLite.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseTypeLite.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/JurisdictionRepositoryTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/TestHelper.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/UserRoleControllerTest.java
Labels: bug
