Repository hmcts/ccd-definition-store-api, pull requests merged in 2019-04, with the labels that each got.

#353 RDM-3951-CaseType-Performance improvement for fixedListItems
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/casetype/mapper/FieldTypeListItemMapper.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeEntity.java
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/BaseTypeController.java
Labels: ns:ccd-definition-store-api-pr-353, performance

#354 Add DB indexes to all top queries
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-3681.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-4029.xml
Labels: ns:ccd-definition-store-api-pr-354, performance

#374 change idam_api_url to SIDAM
  infrastructure/sprod.tfvars
Labels: ns:ccd-definition-store-api-pr-374

#384 Switch SIDAM
  infrastructure/demo.tfvars
Labels: ns:ccd-definition-store-api-pr-384

#385 Update docker health checker
  Dockerfile
Labels: ns:ccd-definition-store-api-pr-385

#390 RDM-4610: CVE-2019-0232 fix
  build.gradle
  infrastructure/main.tf
Labels: ns:ccd-definition-store-api-pr-390

#370 RDM-4362 create PR for liquibase changes
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-4362.xml
Labels: ns:ccd-definition-store-api-pr-370
