Repository hmcts/ccd-definition-store-api, pull requests merged in 2019-02, with the labels that each got.

#273 Enable Helm charts
  Dockerfile
  Jenkinsfile_CNP
  charts/ccd-definition-store-api/Chart.yaml
  charts/ccd-definition-store-api/requirements.lock
  charts/ccd-definition-store-api/requirements.yaml
  charts/ccd-definition-store-api/values.aat.template.yaml
  charts/ccd-definition-store-api/values.template.yaml
Labels: ns:ccd-definition-store-api-pr-273

#280 Bump se.patrikerdes.use-latest-versions from 0.2.3 to 0.2.7
  build.gradle
Labels: ns:ccd-definition-store-api-pr-280

#282 Bump Gradle to 4.10.3
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:ccd-definition-store-api-pr-282

#288 Switch to SIDAM for testing
  charts/ccd-definition-store-api/requirements.lock
  charts/ccd-definition-store-api/requirements.yaml
  infrastructure/saat.tfvars
Labels: ns:ccd-definition-store-api-pr-288

#287 RDM-3479: Definitive Case Type ID check on Definition import
  domain/build.gradle
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/casetype/CaseTypeService.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/casetype/CaseTypeServiceImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationErrorMessageCreator.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityReferenceSpellingValidationError.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/casetype/CaseTypeServiceImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityReferenceSpellingValidationErrorTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreatorTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeRepository.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeRepositoryTest.java
Labels: checkpoint, ns:ccd-definition-store-api-pr-287

#297 Use Kubernetes friendly Java image
  Dockerfile
Labels: ns:ccd-definition-store-api-pr-297

#306 Align Dockerfile and hub.Dockerfile
  Dockerfile
  hub.Dockerfile
Labels: ns:ccd-definition-store-api-pr-306

#259 RDM-3487 - cross case type search - limit results
  application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V34.json
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseType.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/SearchAliasField.java
Labels: ns:ccd-definition-store-api-pr-259

#312 upgraded pmd tool version to 6.11.0 (CVE-2019-7722)
  build.gradle
Labels: bug

#310 RDM-4108 Definition Store to create new import format definition for …
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/BaseTest.java
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/excel/SpreadSheetImportTest.java
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/BaseTypeControllerTests.java
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/MultipleControllersEndpointIT.java
  application/src/test/resources/CCD_TestDefinition_V39_RDM-3317.xlsx
  application/src/test/resources/CCD_TestDefinition_V40_RDM-4108.xlsx
  application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V35.json
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationErrorMessageCreator.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefield/EventCaseFieldCaseHistoryViewerCaseFieldValidator.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefield/EventCaseFieldCaseHistoryViewerCaseFieldValidatorTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreatorTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  excel-importer/src/test/resources/CCD_TestDefinition.xlsx
  excel-importer/src/test/resources/CCD_TestDefinition_V12.xlsx
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-4108.xml
Labels: checkpoint
