Repository hmcts/ccd-definition-store-api, pull requests merged in 2020-10, with the labels that each got.

#747 Befta fw bump up
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-747

#745 RDM 9555 FTA
  aat/src/aat/resources/features/F-090/F-090.feature
  aat/src/aat/resources/features/F-092 Conditional Event Post State/F-092.feature
  aat/src/aat/resources/features/F-092 Conditional Event Post State/F-092_Test_Base_data.td.json
  aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.1.td.json
  aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.2.td.json
  aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.3.td.json
  aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.4.td.json
  aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.5.td.json
  aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.6.td.json
  aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.7.td.json
  build.gradle
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/RestResponseEntityExceptionHandler.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-745

#752 Upgrade to latest, fixed fw version.
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-752

#753 Removed @Ignore for @S-089.1
  aat/src/aat/resources/features/F-089/F-089.feature
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-753

#754 Removed PMD reference
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/SwaggerGeneratorTest.java
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-754

#755 Rdm 9551 tf onto develop
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-755

#760 bump up hmcts plugin
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-760

#768 Disable gssEncMode
  charts/ccd-definition-store-api/values.yaml
  liquibase.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-768

#758 Rdm 9052
  aat/src/aat/resources/features/F-000/S-000.td.json
  application/build.gradle
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/AliasWebConfig.java
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/SecurityConfiguration.java
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/SwaggerConfiguration.java
  application/src/main/resources/application.properties
  build.gradle
  charts/ccd-definition-store-api/Chart.yaml
  integration-tests/build.gradle
  liquibase.gradle
  repository/build.gradle
  repository/src/main/resources/db/changelog/db.changelog-0.0.13.xml
  repository/src/main/resources/db/changelog/db.changelog-0.0.14.xml
  repository/src/main/resources/db/changelog/db.changelog-0.0.15.xml
  repository/src/main/resources/db/changelog/db.changelog-0.0.5.xml
  repository/src/main/resources/db/changelog/db.changelog-0.0.8.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-1074.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-1345.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-2835.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-2917.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-2918.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-3317.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-3327.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-4084.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-6719.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-6965.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-8509.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9031.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9338.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9555.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-758

#778 RDM-9824: Validchecksum tag added to 9031 and 9555
  repository/src/main/resources/db/changelog/db.changelog-rdm-9031.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9555.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-778

#777 RDM-9925 FTA
  aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/F-094.feature
  aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/F-094_Definition_Import_Test_Base_data.td.json
  aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/S-094.5.td.json
  aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/S-094.6.td.json
  aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/S-094.7.td.json
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-777

#784 suppress temporarily
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-784

#781 Aca 68 - Add MCA to list of S2S authorised services
  README.md
  application/src/main/resources/application.properties
  charts/ccd-definition-store-api/values.yaml
  docker-compose.yml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-781
