Repository hmcts/ccd-definition-store-api, pull requests merged in 2020-06, with the labels that each got.

#618 RDM-8509 search case results field tab
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayService.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayServiceTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/GenericLayoutParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/LayoutParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchCasesResultLayoutParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchInputLayoutParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchResultLayoutParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/WorkbasketInputLayoutParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/WorkbasketLayoutParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/model/DefinitionDataItem.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/SheetName.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SpreadSheetValidationMappingEnum.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/GenericLayoutParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/LayoutParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchCasesResultLayoutParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchInputLayoutParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchResultLayoutParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/WorkbasketInputLayoutParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/WorkbasketLayoutParserTest.java
  excel-importer/src/test/resources/CCD_TestDefinition.xlsx
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/GenericLayoutRepository.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/SearchCasesResultFieldEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/SearchCasesResult.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/SearchCasesResultField.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-8509.xml
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/GenericLayoutRepositoryTest.java
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiController.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiControllerTest.java
Labels: ns:ccd, rel:ccd-definition-store-api-pr-618

#619 Empty Commit
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-definition-store-api-pr-619

#620 RDM-8552 - Add last_state_modified_date ES mapping
  elastic-search-support/src/main/resources/application.yml
Labels: ns:ccd, rel:ccd-definition-store-api-pr-620

#624 Linked F-000 as smoke test
  aat/build.gradle
  aat/src/aat/resources/features/F-000/F-000.feature
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-definition-store-api-pr-624

#626 RDM-8733: CVE-2020-13692
  application/build.gradle
  build.gradle
  dependency-check-suppressions.xml
  integration-tests/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-626

#613 Rdm 8382
  aat/src/aat/resources/features/F-089/S-089.1.td.json
  build.gradle
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterService.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationErrorMessageCreator.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityEventCaseFieldsValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityValidationContext.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefield/EventCaseFieldEntityValidationContext.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefieldcomplextype/EventComplexTypeEntityDefaultValueError.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefieldcomplextype/EventComplexTypeEntityDefaultValueValidatorImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityEventCaseFieldsValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefieldcomplextype/EventComplexTypeEntityDefaultValueValidatorImplTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreator.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventCaseFieldComplexTypeParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventCaseFieldComplexTypeParserTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventComplexTypeEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/GlobalCaseRole.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseEventFieldComplex.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/WizardPageComplexFieldOverride.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-8382.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-613

#629 RDM-8581 : Updating total-fields.limit
  elastic-search-support/src/main/resources/casesIndexSettings.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-629

#634 RDM-8814: Data store develop branch code coverage issue
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-634

#632 RDM-8581 : Updating total-fields.limit
  dependency-check-suppressions.xml
  elastic-search-support/src/main/resources/casesIndexSettings.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-632

#630 Rdm 8667
  Jenkinsfile_CNP
  aat/build.gradle
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/EmptySmokeTest.java
  aat/src/aat/resources/features/F-080/S-080.1.td.json
  aat/src/aat/resources/features/F-086/S-375.td.json
  aat/src/aat/resources/features/F-089/F-089.feature
  aat/src/aat/resources/features/F-089/F-089_Test_Base_data.td.json
  aat/src/aat/resources/features/F-089/S-089.1.td.json
  aat/src/aat/resources/features/F-089/S-089.2.td.json
  aat/src/aat/resources/features/F-089/S-089.3.td.json
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-630
