Repository hmcts/ccd-definition-store-api, pull requests merged in 2020-12, with the labels that each got.

#841 Rdm 10294 master
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-841

#848 Release cut 20.2 revised update develop
  aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/F-094_Definition_Import_Test_Base_data.td.json
  application/src/main/resources/application.properties
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/excel/SpreadSheetImportTest.java
  application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V46.json
  dependency-check-suppressions.xml
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/ServicesAutowiringTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9741.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9824.xml
  repository/src/main/resources/db/lb_changelog_temp/db.changelog-master.xml
  repository/src/main/resources/db/lb_changelog_temp/db.changelog-rdm-9031.xml
  repository/src/main/resources/db/lb_changelog_temp/db.changelog-rdm-9555.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-848

#851 RDM-10492: Move liquibase db changelogs in 20.2 to Flyway migrations
  repository/src/main/resources/db/migration/V0001__Base_version.sql
  repository/src/main/resources/db/migration/V20201209__RDM-10429-challenge_question.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-851

#816 RDM-10161 - Create PreviousOrganisation complex type
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java
  repository/src/main/resources/db/migration/V0002__RDM-10161.sql
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-816

#829 ACA-112 - bump befta-fw to 6.2.0
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-829

#852 RDM-10549 Fix CVEs Newly Reported on All 4 Java Apps
  build.gradle
  charts/ccd-definition-store-api/values.preview.template.yaml
  commons/build.gradle
  dependency-check-suppressions.xml
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/Jurisdiction.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/Version.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-852

#849 [New] RDM-10044 - publish column on case event tab
  aat/src/aat/resources/features/F-079/S-508.td.json
  aat/src/aat/resources/features/F-093/S-600.3.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/F-095_Publish_Flag_In_Case_Event.feature
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.2.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.3.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.3_Get_CaseType.td.json
  aat/src/aat/resources/features/common/Get_CaseType.td.json
  aat/src/aat/resources/features/common/Import_Base_data.td.json
  application/src/main/resources/application.properties
  application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V45.json
  build.gradle
  charts/ccd-definition-store-api/values.preview.template.yaml
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/ApplicationParams.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseEvent.java
  repository/src/main/resources/db/migration/V20201207__RDM-10044_publish_column.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-849

#857 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-857

#863 RDM-10261 Update COR.CaseRoleId from Text to DynamicList type
  repository/src/main/resources/db/migration/V20201208__RDM-10261_COR_CaseRoleId_DynamicList.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-863

#868 Update build.gradle
  build.gradle
  repository/src/main/resources/db/migration/V20201217__RDM-10161_previous_organisations.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-868

#874 RDM-10386 updated DEFINITION_STORE_DB_MAX_POOL_SIZE to 25
  charts/ccd-definition-store-api/Chart.yaml
  charts/ccd-definition-store-api/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-874

#880 deleted unwanted liquibase files
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9741.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9824.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-880
