Repository hmcts/ccd-definition-store-api, pull requests merged in 2020-01, with the labels that each got.

#499 RDM-7150: Fix tomcat security issues on ccd-data-store and ccd-defini…
  build.gradle
Labels: ns:ccd-definition-store-api-pr-499

#503 Fixing in sonar error.
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationError.java
Labels: ns:ccd-definition-store-api-pr-503

#504 increasing mem for def store on Preview to avoid out of mem during im…
  charts/ccd-definition-store-api/values.preview.template.yaml
Labels: ns:ccd-definition-store-api-pr-504

#506 Rdm 7196 second attempt
  charts/ccd-definition-store-api/values.preview.template.yaml
Labels: ns:ccd-definition-store-api-pr-506

#505 Perftest fix
  charts/ccd-definition-store-api/values.yaml
Labels: ns:ccd-definition-store-api-pr-505

#492 RDM-6719: Add Banner Feature to CCD UI
  application/src/test/resources/CCD_TestDefinition_V46_RDM-4324.xlsx
  application/src/test/resources/ccd-definition-wrong-complex-type.xlsx
  application/src/test/resources/ccd_testdefinition-missing-WorkBasketResultFields.xlsx
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/JurisdictionServiceImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerService.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerServiceImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/ServicesAutowiringTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/BannerParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/SheetName.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/BannerParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SpreadsheetParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  excel-importer/src/test/resources/CCD_TestDefinition.xlsx
  excel-importer/src/test/resources/CCD_TestDefinition_V12.xlsx
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/BannerRepository.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/BannerEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/Banner.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/BannersResult.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/Jurisdiction.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-6719.xml
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiController.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DraftDefinitionControllerTest.java
Labels: ns:ccd-definition-store-api-pr-492

#510 RDM-7116 rm-ase-envir
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ccd-definition-store-api-pr-510

#511 Removed unwanted env (ASE) files
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:ccd, rel:ccd-definition-store-api-pr-511

#515 RDM-7289 - Update jackson-databind
  build.gradle
Labels: ns:ccd, rel:ccd-definition-store-api-pr-515

#517 Revert "Removed unwanted env (ASE) files"
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:ccd, rel:ccd-definition-store-api-pr-517

#521 Rdm 7380: Fix code coverage issue on Banner Changes
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerServiceImplTest.java
Labels: ns:ccd, rel:ccd-definition-store-api-pr-521

#522 RDM-7406 - Resolve CVE-2020-5398
  build.gradle
Labels: ns:ccd, rel:ccd-definition-store-api-pr-522

#524 suppressed CVE-2020-5398 temporarily
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-definition-store-api-pr-524
