Repository hmcts/ccd-definition-store-api, pull requests merged in 2020-05, with the labels that each got.

#565 Added the initial Files for Mutation Testing
  Jenkinsfile_nightly
  aat/build.gradle
  app-insights/build.gradle
  application/build.gradle
  build.gradle
  domain/build.gradle
  elastic-search-support/build.gradle
  repository/build.gradle
  rest-api/build.gradle
Labels: ns:ccd, rel:ccd-definition-store-api-pr-565

#583 Rdm 8007
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-definition-store-api-pr-583

#611 Fix CVE-2020-9488
  build.gradle
Labels: ns:ccd, rel:ccd-definition-store-api-pr-611

#584 RDM-8003: CCD-Definition-store-api -Fix CVEs Spring Framework 5.0.5.R…
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-definition-store-api-pr-584

#590 Rdm 8002
  application/build.gradle
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/BaseTest.java
  build.gradle
  commons/build.gradle
  commons/src/main/java/uk/gov/hmcts/ccd/definition/store/JacksonUtils.java
  dependency-check-suppressions.xml
  repository/build.gradle
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/DefinitionModelMapper.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/model/DefinitionModelMapperTest.java
  settings.gradle
Labels: ns:ccd, rel:ccd-definition-store-api-pr-590

#606 RDM-7650 use JSON Def file functionality in befta
  Jenkinsfile_CNP
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, rel:ccd-definition-store-api-pr-606

#607 RDM-8393 update health-spring-boot-starter
  build.gradle
Labels: ns:ccd, rel:ccd-definition-store-api-pr-607

#616 Update build.gradle
  build.gradle
Labels: ns:ccd, rel:ccd-definition-store-api-pr-616

#614 RDM-8127 RDM-8359 New base types: Organisation and OrganisationPolicy
  aat/src/aat/resources/features/F-089/F-089.feature
  aat/src/aat/resources/features/F-089/F-089_Test_Complex_Organisation.td.json
  aat/src/aat/resources/features/F-089/S-089.1.td.json
  build.gradle
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java
  repository/src/main/resources/db/changelog/db.changelog-master.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-8127.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-8359.xml
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
Labels: ns:ccd, rel:ccd-definition-store-api-pr-614
