Repository hmcts/ccd-definition-store-api, pull requests merged in 2021-03, with the labels that each got.

#954 fix mistakenly broken imports
  aat/src/aat/resources/features/F-077/S-331.td.json
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-954

#952 RDM-11234 Upgrade Hikari CP Dependency in All CCD Apps
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-952

#884 RDM-3079: Search by case id not working with hyphens
  elastic-search-support/src/main/resources/application.yml
  elastic-search-support/src/main/resources/casesIndexSettings.json
  elastic-search-support/src/test/resources/integration/case_type_mapping.json
  elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json
  elastic-search-support/src/test/resources/integration/single_casetype_index.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-884

#951 RDM-10937: Change [CASE REFERENCE] metadata field type from 'Number' …
  aat/src/aat/resources/features/F-079/S-508.td.json
  aat/src/aat/resources/features/F-080/S-080.1.td.json
  aat/src/aat/resources/features/F-089/S-089.2.td.json
  aat/src/aat/resources/features/F-090/S-090.3.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.3_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.8_Get_CaseType.td.json
  application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V35.json
  application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V45.json
  repository/src/main/resources/db/migration/V20210224_10937__RDM-10937_case_reference_field_type.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-951

#959 RDM-11362 CVE-2020-26939 (Definition Store)
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-959

#963 RDM-11506 CVE-2021-25122 (Def Store)
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-963

#962 RDM-11506 CVE-2021-25122 (Def Store)
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-962

#938 RDM-11046 Update OrganisationPolicy: Defaulting the Organisation for Case Creator
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
  dependency-check-suppressions.xml
  repository/src/main/resources/db/migration/V20210219_11046__RDM-11046_prepopulate_to_users_organisation.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-938

#926 RDM-10262 Update ChangeOrganisationRequest import validations
  Jenkinsfile_CNP
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreTestAutomationAdapter.java
  aat/src/aat/resources/features/F-093/S-600.1.td.json
  aat/src/aat/resources/features/F-093/S-600.2.td.json
  aat/src/aat/resources/features/F-093/S-600.3.td.json
  aat/src/aat/resources/features/F-093/S-600.4.td.json
  aat/src/aat/resources/features/F-093/S-600.5.td.json
  aat/src/aat/resources/features/F-093/S-600.6.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
  aat/src/aat/resources/features/F-096/F-096.feature
  aat/src/aat/resources/features/F-096/S-096.1.td.json
  aat/src/aat/resources/features/F-096/S-096.2.td.json
  aat/src/aat/resources/features/common/Test_Base_data.td.json
  build.gradle
  charts/ccd-definition-store-api/values.preview.template.yaml
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationErrorMessageCreator.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityCORValidationError.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityCORValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityCaseTypeUserRoleValidationError.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityCaseTypeUserRoleValidatorImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityCORValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityCaseTypeUserRoleValidatorImplTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreatorTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-926

#964 Rdm 11544
  elastic-search-support/src/main/resources/application.yml
  elastic-search-support/src/test/resources/integration/case_type_mapping.json
  elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json
  elastic-search-support/src/test/resources/integration/single_casetype_index.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-964

#973 RDM-11765 Update CVE Suppress Until Date In All Services
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-973

#975 RDM-11090: CCD-DEFINITION-STORE: Upgrade to Postgres 11 on ITHC
  build.gradle
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-975

#915 RDM-10538: Introduce RoleToAccessProfiles tab to definition store
  aat/src/aat/resources/features/F-079/S-508.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.3_Get_CaseType.td.json
  aat/src/aat/resources/features/F-097 RoleToAccessProfiles/F-097.feature
  aat/src/aat/resources/features/F-097 RoleToAccessProfiles/F-097_Test_Base_data.td.json
  aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.1.td.json
  aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.2.td.json
  aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.3.td.json
  aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.4.td.json
  aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.5.td.json
  build.gradle
  charts/ccd-definition-store-api/values.preview.template.yaml
  dependency-check-suppressions.xml
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/accessprofiles/RoleToAccessProfileService.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/accessprofiles/RoleToAccessProfilesServiceImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/ServicesAutowiringTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/accessprofiles/RoleToAccessProfilesServiceImplTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/RoleToAccessProfilesParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/SheetName.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/RoleToAccessProfilesValidator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/RoleToAccessProfilesParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/validation/RoleToAccessProfilesValidatorTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/RoleToAccessProfilesRepository.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/RoleToAccessProfilesEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseType.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/RoleToAccessProfiles.java
  repository/src/main/resources/db/migration/V20210202_10538__RDM-10538_role_to_access_profiles.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-915
