Repository hmcts/ccd-definition-store-api, pull requests merged in 2021-04, with the labels that each got.

#977 RDM-11933: Case reference type changed to TEXT
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-977

#982 Update main.tf fix-demo
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-982

#986 Fix develop build
  charts/ccd-definition-store-api/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-986

#980 RDM-12014 update labels to include spaces in previous organisations
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
  repository/src/main/resources/db/migration/V20210413_12014__RDM-12014_previous_organisations.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-980

#988 RDM-12131 Extend Expiry Dates of All CVE Suppressions in CCD Repos
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-988

#987 RDM-12168 CVE-2021-29425 - bump up dependencies to resolve CVE
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-987

#989 RDM-12107 Fortify Issue 13318076 - Unreleased Resource: Streams - High
  elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/client/HighLevelCCDElasticClient.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-989

#981 RDM-12014 update labels to include spaces in previous organisations
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
  repository/src/main/resources/db/migration/V20210413_12014__RDM-12014_previous_organisations.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-981

#992 CCD-961 Merge Controller Advices in Def Store
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ControllerExceptionHandler.java
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/exceptions/RestEndPointExceptionHandler.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/AdminWebAuthorizationControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/CaseDefinitionControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ControllerExceptionHandlerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DraftDefinitionControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/IdamProfileControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ImportAuditControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/UserRoleControllerTest.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/exceptions/RestEndPointExceptionHandlerTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-992
