Repository hmcts/ccd-definition-store-api, pull requests merged in 2021-11, with the labels that each got.

#1091 Update Jenkinsfile_CNP syncBranchesWithMaster
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1091

#1096 CCD-2113: Address CVE-2021-42340
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1096

#1097 CCD-2138: Address CVE-2021-22096
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1097

#1099 CCD-2132: Remove suppression of CVE-2021-22147
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1099

#1100 CCD-2107: Updated CVE suppression dates
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1100

#1095 CCD-572 Fix for looping issue when fetching Az blob segments
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/service/AzureImportAuditsClient.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/service/AzureImportAuditsClientTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1095
