Repository hmcts/ccd-definition-store-api, pull requests merged in 2021-07, with the labels that each got.

#1030 RDM-12651 - Increase NoC answer field length
  repository/src/main/resources/db/migration/V20210706_12651__RDM-12651_noc_answer_field_length.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1030

#1021 RDM-12585 Fix RoleToAccessProfiles.authorisations
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1021

#991 RDM-11779 Run Definition Store Flyway migrations during app startup
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/flyway/FlywayConfiguration.java
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/flyway/FlywayNoOpStrategy.java
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/flyway/PendingMigrationScriptException.java
  application/src/main/resources/application.properties
  application/src/test/java/uk/gov/hmcts/ccd/definition/store/flyway/FlywayNoOpStrategyTest.java
  build.gradle
  charts/ccd-definition-store-api/Chart.yaml
  charts/ccd-definition-store-api/values.preview.template.yaml
  charts/ccd-definition-store-api/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-991

#1035 remove enableDbMigration from Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1035

#1031 Fix cves
  build.gradle
  dependency-check-suppressions.xml
  elastic-search-support/build.gradle
  elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/client/HighLevelCCDElasticClient.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1031

#1016 CCD-255 Mid event callbacks silently failing
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/ImportDefinitionTest.java
  aat/src/resource/CCD_CNP_27_CaseType_Event_Mid_Event_URL.xlsx
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AbstractDisplayGroupParser.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/DisplayGroupParserTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1016

#1036 fix for CVE-2021-33037
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1036

#1029 RDM-12549: Migrate internal search APIs to Access Profiles
  aat/src/aat/resources/features/F-084/S-364.td.json
  aat/src/aat/resources/features/F-088/S-385.td.json
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/SearchCasesResultField.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/SearchResultsField.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/WorkBasketResultField.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1029

#1039 Tolerate missing def store instances when building first time
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1039

#1037 Nightly master ccd 1592
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1037

#1042 CCD-1330: Updated CVE suppression dates to 25/08/2021
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1042

#1043 Disable test due to perfomance fail
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/CaseTypeTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1043

#1044 Remove test annotaion
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/CaseTypeTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1044

#1045 Suppress apache-commons-compress CVE's
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1045

#1048 Override transitive dependency commons-compress
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1048

#1050 double the storage of def store DB
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1050
