Repository hmcts/ccd-definition-store-api, pull requests merged in 2021-12, with the labels that each got.

#1090 RDM-10133 showCondition support for AND, OR and Parenthesis
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/showcondition/ShowConditionParser.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/showcondition/ShowConditionParserTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1090

#1094 RDM-12834: Update Definition Store to recognise new columns - "CallbcackGetCaseUrl" and "CallbackGetCaseRetriesTimeout" in the CaseType tab
  aat/src/aat/resources/features/F-079/S-508.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.3_Get_CaseType.td.json
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.8_Get_CaseType.td.json
  aat/src/aat/resources/features/F-098 rename of UserRole to AccessProfile/common/F-098_Get_CaseType__Base.td.json
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/CaseTypeParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/CaseTypeParserTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseType.java
  repository/src/main/resources/db/migration/V20210929_12834__RDM-12834_CallbackGetCaseUrl_column.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1094

#1088 RDM-12836: Update Case Definition Import to Allow Injected Show Condi…
  aat/src/aat/resources/features/F-099 INJECTED_DATA/F-099.feature
  aat/src/aat/resources/features/F-099 INJECTED_DATA/F-099_Test_Base_data.td.json
  aat/src/aat/resources/features/F-099 INJECTED_DATA/S-099.1.td.json
  aat/src/aat/resources/features/F-099 INJECTED_DATA/S-099.5.td.json
  aat/src/aat/resources/features/F-099 INJECTED_DATA/S-099.6.td.json
  build.gradle
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/metadata/InjectedField.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/showcondition/ShowCondition.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/complexfield/ComplexFieldEntityShowConditionValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaygroup/PageShowConditionValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaygroup/TabShowConditionValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/genericlayout/GenericLayoutShowConditionValidatorImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/metadata/InjectedFieldTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/showcondition/ShowConditionParserTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/complexfield/ComplexFieldEntityShowConditionValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaygroup/PageShowConditionValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaygroup/TabShowConditionValidatorImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/genericlayout/GenericLayoutShowConditionValidatorTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1088

#1107 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1107

#1047 Introduce useful DB queries into version control
  repository/src/main/resources/db/useful-queries/Find missing indexes.sql
  repository/src/main/resources/db/useful-queries/List create and drop for FK within DB.sql
  repository/src/main/resources/db/useful-queries/Regular queries.sql
  repository/src/main/resources/db/useful-queries/Remove Field Type with Date and Juridiction.sql
  repository/src/main/resources/db/useful-queries/Remove all definitions for a case type older than 3 months, but leaving max version.sql
  repository/src/main/resources/db/useful-queries/Remove all definitions for a case type.sql
  repository/src/main/resources/db/useful-queries/Remove all definitions for a jurisdiction.sql
  repository/src/main/resources/db/useful-queries/list-record-counts.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1047

#1108 update log4j version to 2.15.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1108

#1055 Refactor FetchMode on Definition Store Persistence Calls
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterService.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/complexfield/ComplexFieldEntityOrderValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaygroup/PageShowConditionValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaygroup/TabShowConditionValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/AbstractShowConditionValidator.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefield/EventCaseFieldShowConditionValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/eventcasefieldcomplextype/EventComplexTypeShowConditionValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/genericlayout/GenericLayoutEntityElementPathValidatorImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/genericlayout/GenericLayoutShowConditionValidatorImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/FieldTypeServiceImplTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityFieldLabelValidatorTest.java
  elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/mapping/type/CollectionTypeMappingGenerator.java
  elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/mapping/type/ComplexTypeMappingGenerator.java
  elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/SynchronousElasticDefinitionImportListenerIT.java
  elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/mapping/type/ComplexTypeMappingGeneratorTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationComplexTypeParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/ChallengeQuestionValidator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/LayoutParserTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseFieldEntityUtil.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/Authorisation.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseFieldEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/ComplexFieldEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupCaseFieldEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventCaseFieldEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/GenericLayoutEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/IdGenerator.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/StateACLEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/StateEntity.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseFieldEntityUtilTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepositoryTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeObjectGraphTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseFieldEntityTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/entity/ComplexFieldEntityTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupCaseFieldEntityTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeEntityTest.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/entity/StateACLEntityTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1055

#1109 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1109

#1046 Fix poor performing api
  aat/src/aat/resources/features/F-082/F-082.feature
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1046

#1110 CCD-2231-update-cve-suppression-dates-dec-2021
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1110

#1113 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1113
