Repository hmcts/ccd-definition-store-api, pull requests merged in 2021-01, with the labels that each got.

#888 RDM-10678 temporary suppressions
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-888

#885 RDM-10671: increased HTTP max header size to address issue reported i…
  application/src/main/resources/application.properties
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-885

#832 Release-Cut-20.2.0 Revised
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/ImportDefinitionTest.java
  aat/src/aat/resources/features/F-091/F-091.feature
  aat/src/aat/resources/features/F-091/F-091_Test_Base_data.td.json
  aat/src/aat/resources/features/F-091/S-091.1.td.json
  aat/src/aat/resources/features/F-091/S-091.2.td.json
  aat/src/aat/resources/features/F-091/S-091.3.td.json
  aat/src/aat/resources/features/F-091/S-091.4.td.json
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/excel/SpreadSheetImportTest.java
  application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V46.json
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/nocconfig/NoCConfigService.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/nocconfig/NoCConfigServiceImpl.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ChallengeQuestionDisplayContextParameterValidator.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/ServicesAutowiringTest.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/nocconfig/NoCConfigServiceImplTest.java
  elastic-search-support/src/main/resources/application.yml
  elastic-search-support/src/main/resources/casesIndexSettings.json
  elastic-search-support/src/test/resources/integration/case_type_mapping.json
  elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json
  elastic-search-support/src/test/resources/integration/single_casetype_index.json
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ChallengeQuestionParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/NoCConfigParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/SheetName.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/ChallengeQuestionValidator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/challengequestion/BaseChallengeQuestionTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ChallengeQuestionParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/NoCConfigParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/validation/ChallengeQuestionValidatorTest.java
  gradle/wrapper/gradle-wrapper.properties
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/NoCConfigRepository.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/NoCConfigEntity.java
  repository/src/main/resources/db/changelog/db.changelog-rdm-9741.xml
  repository/src/main/resources/db/changelog/db.changelog-rdm-9824.xml
  repository/src/main/resources/db/migration/V0001__Base_version.sql
  repository/src/main/resources/db/migration/V20201209__RDM-10429-challenge_question.sql
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/NoCConfigRepositoryTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-832

#892 Rdm 10683
  build.gradle
  dependency-check-suppressions.xml
  repository/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-892

#899 RDM-10854 - Update testcontainers for Docker pull fix
  elastic-search-support/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-899

#905 RDM-10879 Set flyway.ignoreMissingMigrations to true.
  application/src/main/resources/application.properties
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-905

#901 RDM-10747 : Swagger Publishing Workflow Broken - Definition Store API
  .github/workflows/swagger.yml
  aat/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-901

#824 Replaced embedded postgres with Test Containers
  README.md
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/TestConfiguration.java
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/MultipleControllersEndpointIT.java
  application/src/test/resources/test.properties
  build.gradle
  integration-tests/src/test/java/uk/gov/hmcts/integration/IntegrationTest.java
  integration-tests/src/test/resources/integration_tests.properties
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/TestConfiguration.java
  repository/src/test/resources/test.properties
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-824

#751 RDM-9754
  aat/src/aat/resources/features/F-086/S-375.td.json
  aat/src/aat/resources/features/F-093/S-600.2.td.json
  aat/src/aat/resources/features/F-093/S-600.4.td.json
  dependency-check-suppressions.xml
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterService.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventCaseFieldComplexTypeParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/model/DefinitionDataItem.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/HiddenFieldsValidator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventCaseFieldComplexTypeParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventParserTest.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/validation/HiddenFieldsValidatorTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventComplexTypeEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/WizardPageComplexFieldOverride.java
  repository/src/main/resources/db/migration/V20201217__RDM-9754_retain_hidden_value_case_event_to_complex_type.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-751

#910 RDM-10843 Add CaseType reference validation
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityReferenceValidator.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityReferenceValidatorTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-910
