Repository hmcts/ccd-definition-store-api, pull requests merged in 2021-05, with the labels that each got.

#972 RDM-9765
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-972

#996 RDM-11095: CCD-DEFINITION-STORE: Upgrade to Postgres 11 on PROD
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-996

#997 RDM-11095: CCD-DEFINITION-STORE: Upgrade to Postgres 11 on AAT
  application/src/main/resources/bootstrap.yaml
  charts/ccd-definition-store-api/values.aat.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-997

#1001 CCD-1137 CVE-2020-10693 on Def Store
  build.gradle
  repository/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1001

#1002 CCD-1137 CVE-2020-10693 on Def Store
  build.gradle
  repository/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1002

#1005 RDM-11095 - Cleanup Definition Store DB migration
  application/src/main/resources/bootstrap.yaml
  charts/ccd-definition-store-api/values.aat.template.yaml
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1005

#1006 update user profile develop pr
  charts/ccd-definition-store-api/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1006

#1008 CCD-1137 CVE-2020-10693 on Def Store
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1008
