Repository hmcts/ccd-definition-store-api, pull requests merged in 2022-09, with the labels that each got.

#1278 Suppress CVE-2022-25857 in suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1278

#1276 Ccd 3577 cleanup CVE suppressions
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1276

#1280 CCD-3429 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1280

#1282 Revert "CCD-3539-CCD-3574: Stop running Nightly builds on weekends, Removal of FTs"
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1282

#1284 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1284

#1272 Ccd 3509 CVE 2021 22044
  aat/build.gradle
  application/build.gradle
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/SwaggerConfiguration.java
  application/src/main/resources/application.properties
  application/src/test/java/uk/gov/hmcts/ccd/definition/store/SwaggerConfigurationTest.java
  build.gradle
  commons/build.gradle
  dependency-check-suppressions.xml
  domain/build.gradle
  elastic-search-support/build.gradle
  elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/ElasticsearchBaseTest.java
  excel-importer/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  integration-tests/build.gradle
  repository/build.gradle
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/VersionedDefinitionRepositoryDecorator.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/TestConfiguration.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/VersionedDefinitionRepositoryDecoratorTest.java
  repository/src/test/resources/test.properties
  rest-api/build.gradle
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/service/AzureImportAuditsClientTest.java
  src/test/java/uk/gov/hmcts/ccd/definition/store/SmokeTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1272

#1290 Fix Parser performance issue
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseEventParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseStateParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationComplexTypeParser.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1290

#1289 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1289

#1292 CCD-3736: Suppress CVE-2022-38752
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1292
