Repository hmcts/ccd-definition-store-api, pull requests merged in 2022-06, with the labels that each got.

#1231 CCD-3209: Switch to non-root user in Dockerfile
  Dockerfile
  docker/database/Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1231

#1234 CCD-3376 update java chart version
  charts/ccd-definition-store-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1234

#1235 CCD-3387 Remove CVE Suppress Until Date from All Services
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1235

#1237 CCD-3248 Monthly Review of All Security Flags - Commented out all sup…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1237

#1238 CCD-3384 Flags field type does not retain values for hidden sub-field
  repository/src/main/resources/db/migration/V20220622_3384__CCD-3384_Update_retain_hidden_values_for_Flags_field_type.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1238

#1241 Update dependency-check-suppressions.xml added temporary suppression for CVE-2022-34305
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1241

#1243 CCD-3343 update the AAT and staging resource configuration to match w…
  charts/ccd-definition-store-api/values.aat.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1243
