Repository hmcts/ccd-definition-store-api, pull requests merged in 2022-12, with the labels that each got.

#1318 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
  commons/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1318

#1320 CCD-4047-Fix-CVE-2022-41946
  application/build.gradle
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1320

#1323 CCD-4068: Removed deletion queries for table noc_config
  repository/src/main/resources/db/useful-queries/Remove all definitions for a case type older than 3 months, but leaving max version.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1323

#1324 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped java v…
  charts/ccd-definition-store-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1324

#1321 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1321
