Repository hmcts/ccd-definition-store-api, pull requests merged in 2022-08, with the labels that each got.

#1264 Update ccd-test-definitions to 7.19.3
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1264

#1263 CCD-3511 CVE-2020-15522 bouncycastle version upgraded to 1.70, suppre…
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1263

#1257 CCD-3539-CCD-3574: Stop running Nightly builds on weekends, Removal of FTs
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1257

#1269 CCD-3604: Temporarily suppress CVE-2022-31197
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1269

#1270 CCD-3612: Fix preview deployment issues
  charts/ccd-definition-store-api/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1270

#1271 CCD-3604: CVE-2022-31197 - Upgraded org.postgresql to 42.4.1 and removed temp suppression
  application/build.gradle
  build.gradle
  dependency-check-suppressions.xml
  integration-tests/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1271

#1273 Add backstage configuration file
  catalog-info.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1273
