Repository hmcts/ccd-definition-store-api, pull requests merged in 2022-04, with the labels that each got.

#1194 RDM-13136
  aat/src/aat/resources/features/F-107 CaseLink/F-107.feature
  aat/src/aat/resources/features/F-107 CaseLink/F-107_Get_CaseType.td.json
  aat/src/aat/resources/features/F-107 CaseLink/S-107.1.td.json
  aat/src/aat/resources/features/F-107 CaseLink/S-107.1_Get_CaseType.td.json
  charts/ccd-definition-store-api/values.preview.template.yaml
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  excel-importer/src/test/resources/CCD_TestDefinition.xlsx
  repository/src/main/resources/db/migration/V20220314_13136__RDM-13136-add_new_subfields_to_CaseLink_complex_field.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1194

#1199 bump up spring fw version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1199

#1206 Elasticsearch-7.16.2.jar suppression
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1206

#1205 New Dates
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1205

#1202 jackson.version update for CVE-2020-36518
  build.gradle
  commons/build.gradle
  dependency-check-suppressions.xml
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/JsonUtils.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/JsonUtilsTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1202
