Repository hmcts/ccd-definition-store-api, pull requests merged in 2022-11, with the labels that each got.

#1303 CCD-3853 run FTAs against next test definition release
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1303

#1308 CCD-3917 CVE-2022-31690, CVE-2022-31690 CCD-3918 CVE-2022-42252 Suppr…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1308

#1299 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1299

#1298 created ExceptionHandlingFilter in Security Filter chain
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/SecurityConfiguration.java
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/security/filters/ExceptionHandlingFilter.java
  application/src/test/java/uk/gov/hmcts/ccd/definition/store/security/filters/ExceptionHandlingFilterTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1298

#1281 CCD-3600 Ignore NULL fields for Challenge Questions
  aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/S-094.1.td.json
  build.gradle
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ChallengeQuestionParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ChallengeQuestionParserTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/ChallengeQuestionTabEntity.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/ChallengeQuestion.java
  repository/src/main/resources/db/migration/V20220905_3600__CCD-3600_Validation_for_NoC.sql
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/ChallengeQuestionTabRepositoryTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1281

#1310 CCD-3918 CVE-2022-42252
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1310

#1312 CCD-3951 Increase Elasticsearch Field Limit
  charts/ccd-definition-store-api/values.yaml
  elastic-search-support/src/main/resources/application.yml
  elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json
  elastic-search-support/src/test/resources/integration/single_casetype_index.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1312

#1311 CCD-3917 Spring Security Upgrade
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1311

#1307 CCD-3533 Add suppressCves task
  .github/workflows/dependency-check.yml
  build.gradle
  gradle/suppress.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1307

#1305 CCD-3744 and CCD 3745 introduce CreatedBy and LastNoCRequestedBy
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
  repository/src/main/resources/db/migration/V20221025_3744__CCD-3744_update_ChangeOrganisationRequest_to_include_created_by.sql
  repository/src/main/resources/db/migration/V20221025_3745__CCD-3745_update_organisation_policy_to_include_requested_by.sql
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-definition-store-api-pr-1305

#1313 CCD-3734 - Upgrade test version to 7.19.9
  build.gradle
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-definition-store-api-pr-1313

#1301 CCD-3828: Add Gradle runRemoteDemo() task
  .gitignore
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1301

#1316 CCD-3916 Update Github actions in workflow - dev branch added and on …
  .github/workflows/codecov.yml
  .github/workflows/scheduled-dummy-commit.yml
  .github/workflows/swagger.yml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1316
