Repository hmcts/ccd-definition-store-api, pull requests merged in 2022-10, with the labels that each got.

#1286 CCD 3658 CVE 2022 25857 fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1286

#1291 CCD-3686 New Judicial User base type
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java
  repository/src/main/resources/db/migration/V20220923_3686__CCD-3686__JudicialUser.sql
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1291

#1294 CCD-3776: Suppress CVE-2022-42003 and CVE-2022-42004
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1294

#1293 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1293, keep-helm

#1275 Fix AuthorisationCaseFieldParser performance issue
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseEventParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseFieldParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseStateParser.java
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationComplexTypeParser.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1275

#1297 CCD-3776 CVE-2022-42003 and CVE-2022-42004 Dependency Check failing p…
  build.gradle
  commons/build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1297
