Repository hmcts/ccd-definition-store-api, pull requests merged in 2023-05, with the labels that each got.

#1372 CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1372

#1378 CCD-4515- Modify FlagDetail
  repository/src/main/resources/db/migration/V20230510_4515__CCD-4515__AmendFlagDetails.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1378

#1380 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1380

#1382 CCD-4687 Update renovate.json
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1382
