Repository hmcts/ccd-definition-store-api, pull requests merged in 2023-03, with the labels that each got.

#1351 CCD-4396 : Update .terraform-version and ES Chart version
  infrastructure/.terraform-version
Labels: ns:ccd, prd:ccd, add-or-update, rel:ccd-definition-store-api-pr-1351

#1352 Cfts 4360 master
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/ImportDefinitionTest.java
  aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
  aat/src/resource/CCD_CNP_27_Invalid_CaseRole.xlsx
  aat/src/resource/CCD_CNP_27_Valid_CaseRole.xlsx
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/caserole/CaseRoleEntityFieldValueValidatorImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/caserole/CaseRoleEntityFieldValueValidatorImplTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1352

#1353 update befta-fw version to 8.7.11
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1353

#1355 CCD-4436: Sacle ITHC d/b
  infrastructure/ithc.tfvars
Labels: ns:ccd, prd:ccd, no-changes, rel:ccd-definition-store-api-pr-1355

#1332 CCD-1316: Remove redundant dependency uk.gov.hmcts.reform:properties-…
  application/src/main/resources/application.properties
  application/src/main/resources/bootstrap.yaml
  build.gradle
  charts/ccd-definition-store-api/Chart.yaml
  charts/ccd-definition-store-api/values.preview.template.yaml
  charts/ccd-definition-store-api/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1332

#1365 CCD-4476 : replaced reform-api-docs to cnp-api-docs
  .github/workflows/swagger.yml
  README.md
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1365
