Repository hmcts/ccd-definition-store-api, pull requests merged in 2023-01, with the labels that each got.

#1328 Suppress CVEs
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1328

#1331 CCD-4177 Updating test-definition and beta-fw versions
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1331

#1329 CCD-4163 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1329

#1333 CCD-4210 CVE-2022-45143 - upgrade Tomcat to 9.0.69
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1333

#1334 Update Chart.yaml
  charts/ccd-definition-store-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1334

#1336 CCD-4225 Casefileview and regex issues - extra BaseFieldType Referenc…
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/CategoryIdValidator.java
  excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/validation/CategoryIdValidatorTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1336

#1340 CCD-4283: Bump gradle-java-plugin to 0.12.40
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1340
