Repository hmcts/ccd-definition-store-api, pull requests merged in 2023-11, with the labels that each got.

#1412 remove the retainHiddenValue check as part of ccd-4983
  excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/HiddenFieldsValidator.java
Labels: ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-definition-store-api-pr-1412

#1357 CCD-4454 : CVE-2022-1471 Fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1357

#1414 Adding files for v15 upgrade
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, add-or-update, rel:ccd-definition-store-api-pr-1414

#1409 CCD-4771 : Fix CVE-2023-35116
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1409

#1408 CCD-4970 : Fix CVE-2020-8908
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1408

#1398 Test support endpoint
  application/src/main/resources/application.properties
  application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/TestingSupportControllerIT.java
  application/src/test/resources/CCD_TestDefinition_TestingSupportData.xlsx
  application/src/test/resources/test.properties
  build.gradle
  integration-tests/src/test/resources/integration_tests.properties
  rest-api/build.gradle
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/TestingSupportController.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1398

#1415 Updating subnet suffix
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, no-changes, rel:ccd-definition-store-api-pr-1415

#1417 Update performance test configurations
  infrastructure/perftest.tfvars
Labels: ns:ccd, prd:ccd, no-changes, rel:ccd-definition-store-api-pr-1417

#1418 Changing prod gen to Mem optimised
  infrastructure/aat.tfvars
  infrastructure/prod.tfvars
Labels: ns:ccd, prd:ccd, add-or-update, rel:ccd-definition-store-api-pr-1418

#1419 Add testing-support/cleanup-case-type to security whitelist
  application/src/main/java/uk/gov/hmcts/ccd/definition/store/SecurityConfiguration.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1419

#1421 Updating DB Host reference to V15
  charts/ccd-definition-store-api/values.aat.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1421

#1422 update the label of roleOnCase field to 'Role On Case'
  repository/src/main/resources/db/migration/V20231123_4925__CCD-4925_Update_roleOnCase_label.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1422
