Repository hmcts/ccd-definition-store-api, pull requests merged in 2024-03, with the labels that each got.

#1447 CVE fixes 010224
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1447

#1456 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1456

#1457 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1457

#1345 CCD-267: Implement back-end Delete Role functionality
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/AccessProfileService.java
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/AccessProfileServiceImpl.java
  domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/AccessProfileServiceImplTest.java
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/UserRoleController.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/UserRoleControllerTest.java
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-definition-store-api-pr-1345, enable_keep_helm

#1453 Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 9.0.82
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1453
