Repository hmcts/ccd-definition-store-api, pull requests merged in 2024-07, with the labels that each got.

#1482 Update SmokeTest.java - Attempt to create dummy smoke test class to fix pipeline
  src/test/java/uk/gov/hmcts/ccd/definition/store/SmokeTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1482

#1484 increase smoke test timeout to 20 mins
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1484

#1476 Befta-fw 9.0.2, ccd-test-definitions 7.22.2, gradle 8.7
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  aat/build.gradle
  aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreBeftaRunner.java
  aat/src/aat/resources/features/F-090/F-090.feature
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1.td.json
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.3.td.json
  app-insights/build.gradle
  application/build.gradle
  build.gradle
  domain/build.gradle
  elastic-search-support/build.gradle
  excel-importer/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  repository/build.gradle
  rest-api/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1476

#1488 Update .terraform-version to 1.9.2, update azuread to 2.53.1
  infrastructure/.terraform-version
  infrastructure/state.tf
Labels: ns:ccd, prd:ccd, prod/add-or-update, aat/add-or-update, rel:ccd-definition-store-api-pr-1488

#1489 fix master failing Fts
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1.td.json
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.3.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1489

#1491 fixing missing citizen data in excel for FT tests
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1491
