Repository hmcts/ccd-definition-store-api, pull requests merged in 2024-05, with the labels that each got.

#1467 CCD-5468: bumped postgresql to v42.5.5
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1467

#1471 Update perftest cpu
  infrastructure/perftest.tfvars
Labels: ns:ccd, prd:ccd, aat/no-changes, prod/no-changes, rel:ccd-definition-store-api-pr-1471

#1470 DO NOT MERGE- CHG5016403 - increase cpu in db
  infrastructure/prod.tfvars
Labels: ns:ccd, prd:ccd, aat/no-changes, prod/add-or-update, rel:ccd-definition-store-api-pr-1470

#1469 CCD-5472: Fix CVE-2024-25710 bumped commons-compress to 1.26.0
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, aat/no-changes, rel:ccd-definition-store-api-pr-1469, prod/add-or-update

#1455 CCD-5201 Resolving Spring Security CVE
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1455

#1346 CCD-4327 : Addition of tables in delete scripts
  repository/src/main/resources/db/useful-queries/Remove all definitions for a case type older than 3 months, but leaving max version.sql
  repository/src/main/resources/db/useful-queries/Static (Add Foreign Keys).sql
  repository/src/main/resources/db/useful-queries/Static (Drop Foreign Keys).sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1346

#1466 Ccd 4917 add index
  repository/src/main/resources/db/migration/V20240509_4917__CCD-4917_Add_Index.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1466
