Repository hmcts/ccd-definition-store-api, pull requests merged in 2024-04, with the labels that each got.

#1381 update query of findByJurisdictionId
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepository.java
  repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepositoryTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1381

#1452 CCD-5160 : Fix CVE-2023-35116 : bumped jackson.version to 2.16.0
  build.gradle
  commons/build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1452

#1461 Code coverage gitaction removal
  .github/workflows/codecov.yml
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, aat/no-changes, rel:ccd-definition-store-api-pr-1461

#1460 CCD-5201 CVE fixes 34042
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, aat/no-changes, rel:ccd-definition-store-api-pr-1460

#1462 Ccd 5339 pi33 helm chart upgrade chart java
  charts/ccd-definition-store-api/Chart.yaml
  charts/ccd-definition-store-api/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1462
