Repository hmcts/ccd-definition-store-api, pull requests merged in 2024-08, with the labels that each got.

#1472 add new indexes
  repository/src/main/resources/db/migration/V20240522_5501__CCD-5501_Create_new_indexes.sql
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1472

#1498 deprecate /api/data/jurisdictions/{jurisdiction_id}/case-type and dis…
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  aat/src/aat/resources/features/F-081/F-081.feature
  aat/src/aat/resources/features/F-082/F-082.feature
  domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/casetype/CaseTypeServiceImpl.java
  repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeRepository.java
  rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/CaseDefinitionController.java
  rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/CaseDefinitionControllerTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1498

#1486 enable fortify failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1486

#1500 CCD-5624_fix_new
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1500

#1494 Ccd 5647 mismatch for CCD-5233
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1.td.json
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1a.td.json
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1b.td.json
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.3.td.json
  aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.6.td.json
  build.gradle
Labels: ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-definition-store-api-pr-1494

#1501 fix nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1501
