Repository hmcts/ccd-definition-store-api, pull requests merged in 2025-04, with the labels that each got.

#1545 CME-481: Disable sync to ITHC for database monitoring testing
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1545

#1544 CME-481: Add database monitoring
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, aat/add-or-update, ithc/add-or-update, rel:ccd-definition-store-api-pr-1544

#1546 CME-481: Add database monitoring
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, prod/add-or-update, aat/add-or-update, rel:ccd-definition-store-api-pr-1546

#1548 CCD-6286 :: Suppress-CVE-2023-6378
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-definition-store-api-pr-1548
